[package]
name = "abit-parser"
version = "0.0.1"
authors = ["Belz"]
edition = "2018"

[dependencies]
reqwest = "0.11"
scraper = "0.12.0"
anyhow = "1"
futures = "0.3"
pico-args = "0.4"
regex = "1"

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread", "fs"]